name: Deploy to Firebase Hosting on merge
on: 
    push:
      branches: 
        - avaliacaodw-nicolymattos
jobs:
    build_and_deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run:  |
                npm ci && npm run build
        - uses: FirebaseExtended/action-hosting-deploy@v0
          with: 
            repoToken: ${{secrets.FIREBASE_TOKEN}}
            firebaseServiceAccount: ${{secrets.FIREBASE_SERVICE_ACCOUNT_AVALIACAO_LIFEDEV}}
            channelId: live
            projectId: avaliacao-dw3-lifedev